Beining/add command
AY2021S1-CS2103T-T12-3/tp pull request #127
Opened 2020-10-04 04:30 UTC by dearvae

fix #122

2020-10-04 04:47 UTC, MarcTzh commented on src/main/java/seedu/address/model/task/State.java
> +    DONE("done"), PENDING("pending");
Should probably be on separate lines

2020-10-04 04:47 UTC, MarcTzh commented on src/main/java/seedu/address/model/task/State.java
> +    private String string;
Should be named something more meaningful like status or taskStatus

2020-10-04 04:47 UTC, MarcTzh commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
> -        // missing phone prefix
Shall discuss whether these fields should be optional in the team meeting later tonight

2020-10-04 16:20 UTC, BobbyZhouZijian requested changes
Need to fix the documentation first.

2020-10-04 16:20 UTC, BobbyZhouZijian commented on src/main/java/seedu/address/model/task/Description.java
> +     * Constructs a {@code Description}.
Should have clearer documentation here

2020-10-04 16:20 UTC, BobbyZhouZijian commented on src/main/java/seedu/address/model/task/Phone.java
> +     * Constructs a {@code Phone}.
^

2020-10-04 16:20 UTC, BobbyZhouZijian commented on src/main/java/seedu/address/model/task/Status.java
> +     * Constructs a {@code Status}.
Clearer documentation pls.

2020-10-05 01:36 UTC, BobbyZhouZijian reviewed
Generally LGTM. Just some nits to fix

2020-10-05 01:36 UTC, BobbyZhouZijian commented on src/main/java/seedu/address/model/task/Description.java
> +    private static final String DEFAULT_DESCRIPTION = "";
Why is this private variable in between to public variables?

2020-10-05 01:36 UTC, BobbyZhouZijian commented on src/main/java/seedu/address/model/task/Description.java
> +     * Returns if a default Description with empty value;
I think a better documentation is : construct an empty Description when user didn't provide the description field. Caveat: Only called when the user didn't key in this field.

2020-10-05 01:36 UTC, BobbyZhouZijian commented on src/main/java/seedu/address/model/task/Phone.java
> +    private static final String DEFAULT_PHONE = "";
Same. private variable in between public variables.

2020-10-05 01:36 UTC, BobbyZhouZijian commented on src/main/java/seedu/address/model/task/Phone.java
> +     * Returns a default phone object which have empty value
Same. I think the documentation can be better.

2020-10-05 01:36 UTC, BobbyZhouZijian commented on src/test/java/seedu/address/testutil/TaskBuilder.java
> +     * Sets the {@code Phone} of the {@code Task} that we are building to be default phone.
I would recommend making this documentation clearer as well. Add another line to specify that this is only used to construct an empty Phone when the field is not in the task.

2020-10-05 01:36 UTC, BobbyZhouZijian commented on src/test/java/seedu/address/testutil/TaskBuilder.java
> +    public TaskBuilder withDefaultDescription() {
^

2020-10-05 03:44 UTC, BobbyZhouZijian approved these changes
LGTM now.

2020-10-05 03:45 UTC, merged